name: Python CI

# Коли запускати тести:
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest # Тести запускаються на Linux

    steps:
    - name: Копіюємо код репозиторію
      uses: actions/checkout@v4

    - name: Встановлюємо Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Встановлюємо залежності
      run: |
        python -m pip install --upgrade pip
        # Якщо у тебе є файл requirements.txt, розкоментуй рядок нижче:
        # pip install -r requirements.txt
        pip install pytest

    - name: Запускаємо тести через pytest
      run: |
        l1c.py